### ISSUE TITLE
does the authors have any plan to release the code about MiniGPT-v2 for Image captioning and Baichuan2 for Query debiasing?

### ISSUE THREAD

**Issue by onlyonewater** [YoucanBaby/VTG-GPT#1]

**Comment by YoucanBaby** [comment]
Of course, I will release the rest of the code.
In fact, the code for these two parts is very simple. 
But the environment is a bit difficult to configure. I'm checking the environment.

**Comment by onlyonewater** [comment]
oh, that sounds good, I am looking forward to it.

**Comment by YoucanBaby** [comment]
> oh, that sounds good, I am looking forward to it.

done
